import classify
import datetime
from dtw_su import classify

testFiles = [
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Ariyalur.mfcc/1041Ariyalur_1.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Ariyalur.mfcc/1039Ariyalur.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore.mfcc/1059_Coimbatore_1.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore.mfcc/1059Coimbatore_1.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore.mfcc/1058_Coimbatore_2.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore.mfcc/1058_Coimbatore_1.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore.mfcc/1058Coimbatore_1.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore.mfcc/1057Coimbatore_1.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore.mfcc/1056_Coimbatore_.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore.mfcc/1056Coimbatore_1.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore.mfcc/1054_Coimbatore_1.mfcc",
  # "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore.mfcc/1054Coimbatore_1.mfcc"
 "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore_maavat$t$am.mfcc/1084_Coimbatore_maavat$t$am_3.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore_maavat$t$am.mfcc/1084_Coimbatore_maavat$t$am_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore_maavat$t$am.mfcc/1084_Coimbatore_maavat$t$am_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore_maavat$t$am.mfcc/1083Coimbatore_maavat$t$am_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore_maavat$t$am.mfcc/1082_Coimbatore_maavat$t$am_4.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Coimbatore_maavat$t$am.mfcc/1082_Coimbatore_maavat$t$am_3.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Cuddalore.mfcc/1263_Cuddalore_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Cuddalore.mfcc/1263Cuddalore_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Cuddalore.mfcc/1261_Cuddalore_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Dindigul.mfcc/1173Dindigul_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Dindigul.mfcc/1173Dindigul_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Dindigul.mfcc/1169_Dindigul_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Dindigul.mfcc/1169Dindigul_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode.mfcc/1067_Erode_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode.mfcc/1067_Erode_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode.mfcc/1067Erode_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode.mfcc/1066Erode_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode.mfcc/1064_Erode_3.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode.mfcc/1064_Erode_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode.mfcc/1064_Erode_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode.mfcc/1064_Erode_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode.mfcc/1063_Erode_3.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode_maavat$t$am.mfcc/1071_Erode_maavat$t$am_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode_maavat$t$am.mfcc/1071_Erode_maavat$t$am5.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode_maavat$t$am.mfcc/1071Erode_maavat$t$am.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Erode_maavat$t$am.mfcc/1070_Erode_maavat$t$am_5.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Karur.mfcc/1182Karur_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Karur.mfcc/1170_Karur_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Karur.mfcc/1167Karur_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Karur.mfcc/1161Karur_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Karur.mfcc/1103_Karur_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Madurai.mfcc/1197Madurai_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Madurai.mfcc/1171Madurai_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Madurai.mfcc/1131_Madurai_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Namakkal.mfcc/1115Namakkal_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Namakkal.mfcc/1070_Namakkal_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Perambalur.mfcc/1311_Perambalur_4.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Perambalur.mfcc/1311_Perambalur_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Perambalur.mfcc/1311_Perambalur_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Perambalur.mfcc/1310_Perambalur_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Perambalur.mfcc/1310_Perambalur_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Perambalur.mfcc/1310_Perambalur_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Perambalur.mfcc/1309_Perambalur_4.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Perambalur.mfcc/1309_Perambalur_3.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Perambalur.mfcc/1309_Perambalur_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Salem.mfcc/1109Salem_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Salem.mfcc/1108_Salem_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Salem.mfcc/1108Salem_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Salem.mfcc/1107Salem_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Salem.mfcc/1105Salem_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Salem.mfcc/1099Salem_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thanjavur.mfcc/1098Thanjavur_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thanjavur.mfcc/1093Thanjavur_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thanjavur.mfcc/1093Thanjavur_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thanjavur.mfcc/1047Thanjavur_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Theni.mfcc/1046Theni_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Theni.mfcc/1041Theni_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Theni.mfcc/1040Theni_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruchirappalli.mfcc/1133Thiruchirappalli_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruchirappalli.mfcc/1130Thiruchirappalli_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruchirappalli.mfcc/1127Thiruchirappalli_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruchirappalli.mfcc/1121Thiruchirappalli_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruchirappalli.mfcc/1120_Thiruchirappalli_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruchirappalli.mfcc/1120Thiruchirappalli_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruchirappalli.mfcc/1119_Thiruchirappalli.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thirunelveli.mfcc/1266Thirunelveli_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thirunelveli.mfcc/1249_Thirunelveli_4.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thirunelveli.mfcc/1249_Thirunelveli_3.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thirunelveli.mfcc/1249_Thirunelveli_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thirunelveli.mfcc/1249_Thirunelveli_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thirunelveli.mfcc/1249_Thirunelveli_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruvannamalai.mfcc/1270Thiruvannamalai_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruvannamalai.mfcc/1256Thiruvannamalai_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruvarur.mfcc/1301Thiruvarur_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruvarur.mfcc/1297_Thiruvarur_.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruvarur.mfcc/1297Thiruvarur_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Thiruvarur.mfcc/1296Thiruvarur_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Tirupur.mfcc/1200_Tirupur_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Tirupur.mfcc/1102_Tirupur_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Tirupur.mfcc/1102_Tirupur_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Tirupur.mfcc/1095_Tirupur_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Villupuram.mfcc/1099Villupuram_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Villupuram.mfcc/1097Villupuram_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Villupuram.mfcc/1094Villupuram_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Virudhunagar.mfcc/1174Virudhunagar_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Virudhunagar.mfcc/1172Virudhunagar_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Virudhunagar.mfcc/1168Virudhunagar_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Virudhunagar.mfcc/1168Virudhunagar_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Virudhunagar.mfcc/1162Virudhunagar_2.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Virudhunagar.mfcc/1162Virudhunagar_1.mfcc",
  "/Users/subhasis/Documents/iitm_courses/1_st_sem/PR/pr_assignment/assignment_3/dtw/data/test-1/Virudhunagar.mfcc/1160_Virudhunagar_.mfcc"
]
city = classify.do_mem(testFiles)

print(city)



# find_max(database)





